name: .NET Framework Desktop

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Test:
    strategy:
      matrix:
        configuration: [windows-latest]

    runs-on: windows-latest

    env:
      Solution_Name: QuanLyQuanCafe.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup NuGet
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Restore Packages
        run: dotnet restore QuanLyQuanCafe.sln

      - name: Install NUnit Console Runner
        run: dotnet tool install --global NUnit.ConsoleRunner --version 3.12.0

      - name: Execute unit tests
        run: nunit3-console QuanLyQuanCafe.sln

      - name: Create new tool manifest
        run: dotnet new tool-manifest

      - name: Install dotnet stryker
        run: dotnet tool install dotnet-stryker

      - name: Execute mutation tests
        run: dotnet stryker
